application: translate-all-language-at-once
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: _go_app
  secure: always
